#
# PoHessian
# Portable C++ Hessian Implementation
#
# Copyright (C) 2012  Pierre-David Belanger
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contributor(s): Pierre-David Belanger <pierredavidbelanger@gmail.com>
#

ifndef OS
OS = $(shell uname -s)
endif
ifndef ARCH
ARCH = $(shell uname -m)
endif

PROG = libpohessian

TARGET_SHARED = true
TARGET_STATIC = true

CC = g++

CC_WARN = -Wall
CC_PIC = -fPIC

CC_ARCH = 

CC_COMPILE = -c
CC_OUT = -o

CC_FLAGS_OTHER = 

CC_FLAGS_DEBUG = -g -DDEBUG
CC_FLAGS_RELEASE = -O2

CC_FLAGS_SHARED = -shared

AR = ar rvs
RM = rm -rf
MKDIR = mkdir -p
LIPO = lipo

DIR_BUILD = build
DIR_SOURCE = source

DIR_DEBUG = debug
DIR_RELEASE = release

DIR_SHARED = shared
DIR_STATIC = static

SOURCE_EXT = .cpp
OBJECT_EXT = .o
SHARED_EXT = .so
STATIC_EXT = .a

DIR_BUILD_FULL = $(DIR_BUILD)/$(OS)/$(ARCH)

POCO_PATH = ../../lib/poco-1.4.3p1-all
POCO_INCLUDE_PATH = 
POCO_LIBRARY_PATH_DEBUG = 
POCO_LIBRARY_PATH_RELEASE = 

CC_INCLUDE_PATHS = -Iinclude $(POCO_INCLUDE_PATH)

CC_LIBRARY_PATHS_DEBUG = $(POCO_LIBRARY_PATH_DEBUG)
CC_LIBRARY_PATHS_RELEASE = $(POCO_LIBRARY_PATH_RELEASE)

CC_LIBRARY_NAMES_DEBUG = -lPocoFoundationd -lPocoNetd
CC_LIBRARY_NAMES_RELEASE = -lPocoFoundation -lPocoNet

SOURCES = $(shell ls $(DIR_SOURCE)/*$(SOURCE_EXT))

OBJECTS_DEBUG = $(SOURCES:$(DIR_SOURCE)/%$(SOURCE_EXT)=$(DIR_BUILD_FULL)/$(DIR_DEBUG)/%$(OBJECT_EXT))
OBJECTS_RELEASE = $(SOURCES:$(DIR_SOURCE)/%$(SOURCE_EXT)=$(DIR_BUILD_FULL)/$(DIR_RELEASE)/%$(OBJECT_EXT))

SHARED_DEBUG = $(DIR_BUILD_FULL)/$(DIR_DEBUG)/$(DIR_SHARED)/$(PROG)$(SHARED_EXT)
SHARED_RELEASE = $(DIR_BUILD_FULL)/$(DIR_RELEASE)/$(DIR_SHARED)/$(PROG)$(SHARED_EXT)
STATIC_DEBUG = $(DIR_BUILD_FULL)/$(DIR_DEBUG)/$(DIR_STATIC)/$(PROG)$(STATIC_EXT)
STATIC_RELEASE = $(DIR_BUILD_FULL)/$(DIR_RELEASE)/$(DIR_STATIC)/$(PROG)$(STATIC_EXT)
